### ISSUE TITLE
Is this a bug or am I implementing the DynamoDB Attribute interface incorrectly?

### ISSUE THREAD

**Issue by trjate** [cdktf/cdktf-provider-aws-go#1]
```
~/code/learn-cdktf-docker main* ❯ cdktf synth                                                                                                                     

⠹  Synthesizing
[2022-11-12T20:47:11.284] [ERROR] default - Runtime process exited abnormally: wait: no child processes
[2022-11-12T20:47:11.287] [ERROR] default - panic: Passed to parameter config of new @cdktf/provider-aws.dynamodbTable.DynamodbTable: Unable to deserialize value as @cdktf/provider-aws.dynamodbTable.DynamodbTableConfig
├── 🛑 Failing value is an object
│      { '$jsii.struct': [Object] }
╰── 🔍 Failure reason(s):
    ╰─ Key 'attribute': Unable to deserialize value as cdktf.IResolvable | array<@cdktf/provider-aws.dynamodbTable.DynamodbTableAttribute> | undefined
        ├── 🛑 Failing value is an object
        │      { '$jsii.struct': [Object] }
        ╰── 🔍 Failure reason(s):
            ├─ [as array<@cdktf/provider-aws.dynamodbTable.DynamodbTableAttribute>] Value is not an array
            ╰─ [as cdktf.IResolvable] Value does not have the "$jsii.byref" key

goroutine 1 [running]:
github.com/aws/jsii-runtime-go/runtime.Create({0x700352, 0x2f}, {0xc00040fdf0, 0x3, 0x3},
[2022-11-12T20:47:11.287] [ERROR] default - {0x6e9c80, 0xc000015850})
        /home/trevor/go/pkg/mod/github.com/aws/jsii-runtime-go@v1.70.0/runtime/runtime.go:202 +0xa3b
github.com/cdktf/cdktf-provider-aws-go/aws/v10/dynamodbtable.NewDynamodbTable({0x7f4e583d6748?, 0xc000015200}, 0xc0000157e0, 0xc000442500)
        /home/trevor/go/pkg/mod/github.com/cdktf/cdktf-provider-aws-go/aws/v10@v10.0.11/dynamodbtable/dynamodbtable_DynamodbTable.go:858 +0x116
main.createRemoteStateStack({0x7f4e583d6720, 0xc000014f70}, {0x6f5c58, 0x14})
        /home/trevor/code/learn-cdktf-docker/main.go:64 +0x445
main.main()
        /home/trevor/code/learn-cdktf-docker/main.go:90 +0x7b

ERROR: cdktf encountered an error while synthesizing

Synth command: go run main.go
Error:         non-zero exit code 1

Command output on stderr:

    Runtime process exited abnormally: wait: no child processespanic: Passed to parameter config of new @cdktf/provider-aws.dynamodbTable.DynamodbTable: Unable to deserialize value as @cdktf/provider-aws.dynamodbTable.DynamodbTableConfig
    ├── 🛑 Failing value is an object
    │      { '$jsii.struct': [Object] }
    ╰── 🔍 Failure reason(s):
        ╰─ Key 'attribute': Unable to deserialize value as cdktf.IResolvable | array<@cdktf/provider-aws.dynamodbTable.DynamodbTableAttribute> | undefined
            ├── 🛑 Failing value is an object
            │      { '$jsii.struct': [Object] }
            ╰── 🔍 Failure reason(s):
                ├─ [as array<@cdktf/provider-aws.dynamodbTable.DynamodbTableAttribute>] Value is not an array
                ╰─ [as cdktf.IResolvable] Value does not have the "$jsii.byref" key

    goroutine 1 [running]:
    github.com/aws/jsii-runtime-go/runtime.Create({0x700352, 0x2f}, {0xc00040fdf0, 0x3, 0x3}, {0x6e9c80, 0xc000015850})
        /home/trevor/go/pkg/mod/github.com/aws/jsii-runtime-go@v1.70.0/runtime/runtime.go:202 +0xa3b
    github.com/cdktf/cdktf-provider-aws-go/aws/v10/dynamodbtable.NewDynamodbTable({0x7f4e583d6748?, 0xc000015200}, 0xc0000157e0, 0xc000442500)
        /home/trevor/go/pkg/mod/github.com/cdktf/cdktf-provider-aws-go/aws/v10@v10.0.11/dynamodbtable/dynamodbtable_DynamodbTable.go:858 +0x116
    main.createRemoteStateStack({0x7f4e583d6720, 0xc000014f70}, {0x6f5c58, 0x14})
        /home/trevor/code/learn-cdktf-docker/main.go:64 +0x445
    main.main()
        /home/trevor/code/learn-cdktf-docker/main.go:90 +0x7b
    exit status 2

```
```
	dynamoDB := dynamodbtable.NewDynamodbTable(stack, jsii.String("care_co_remote_state_locking"),
		&dynamodbtable.DynamodbTableConfig{
			HashKey:     jsii.String("LockID"),
			Name:        jsii.String("accounts-terraform-state-locking"),
			BillingMode: jsii.String("PAY_PER_REQUEST"),
			Attribute: dynamodbtable.DynamodbTableAttribute{
				Name: jsii.String("LockID"),
				Type: jsii.String("S"),
			},
		})
```

It seems that the `Attribute` field interface wants a list, if I look at the statefile.  

```
"attribute": [
              {
                "name": "LockID",
                "type": "S"
              }
            ],
```
Also that is what the error is telling me:
`            ├─ [as array<@cdktf/provider-aws.dynamodbTable.DynamodbTableAttribute>] Value is not an array`

I've tried converting the `dynamodbtable.DynamodbTableAttribute` struct to a list of structs but I can't get that to work either.

**Comment by trjate** [comment]
Nevermind, I'm an idiot.  This worked for me.

```
	attr := dynamodbtable.DynamodbTableAttribute{
		Name: jsii.String("LockID"),
		Type: jsii.String("S"),
	}
	attrs := []dynamodbtable.DynamodbTableAttribute{}

	attrs = append(attrs, attr)

	dynamoDB := dynamodbtable.NewDynamodbTable(stack, jsii.String("care_co_remote_state_locking"),
		&dynamodbtable.DynamodbTableConfig{
			HashKey:     jsii.String("LockID"),
			Name:        jsii.String("accounts-terraform-state-locking"),
			BillingMode: jsii.String("PAY_PER_REQUEST"),
			Attribute:   attrs,
		})
```
